name: deploy
on:
    workflow_dispatch:

jobs:
    deploy:
    name: Deploy to VPS
    runs-on: debian-12
    steps:
        - name: Deploy
          uses: appleboy/ssh-action@v0.1.8
          with:
                host: 79.143.90.170
                port: 2222
                username: ignacio
                keys: ${{secrets.PRIVATE_KEY}}
                script: "cd /var/www/html/communitylinks; git pull origin master; npm run build"
